# Generated by Django 4.1.7 on 2023-03-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstore', '0006_rename_order_total_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='final_item_price',
        ),
    ]
